/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Joystick_X_Pin_aliases.h"
#include "Joystick_X_Pin.h"
#include "Joystick_X.h"
#include "UART_KitProg.h"
#include "Joystick_Y_Pin_aliases.h"
#include "Joystick_Y_Pin.h"
#include "Joystick_Y.h"
#include "Joystick_Btn_Pin_aliases.h"
#include "Joystick_Btn_Pin.h"
#include "Action0_Btn_Pin_aliases.h"
#include "Action0_Btn_Pin.h"
#include "Action1_Btn_Pin_aliases.h"
#include "Action1_Btn_Pin.h"
#include "DebounceClock.h"
#include "Action1_Btn.h"
#include "Action0_Btn.h"
#include "Joystick_Btn.h"
#include "Joystick_X_IRQ.h"
#include "Joystick_X_theACLK.h"
#include "UART_KitProg_IntClock.h"
#include "Joystick_Y_IRQ.h"
#include "Joystick_Y_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

